### PR TITLE
Models and started challenges page implementation

### PR DESCRIPTION
**Pull request by GregorySech**

### CODE REVIEW

**Comment by GroovinChip** [comment]
Here's what I get when I run `packages get` so I can run your changes:

```C:\flutter\bin\flutter.bat --no-color packages get
Running "flutter packages get" in Flutter-Community-Challenges...
Because no versions of flutter_advanced_networkimage match >0.3.6 <0.4.0 and flutter_advanced_networkimage 0.3.6 depends on quiver ^2.0.0, flutter_advanced_networkimage ^0.3.6 requires quiver ^2.0.0.
And because every version of flutter_test from sdk depends on quiver 0.29.0+1, flutter_advanced_networkimage ^0.3.6 is incompatible with flutter_test from sdk.
So, because flutter_community_challenges depends on both flutter_test any from sdk and flutter_advanced_networkimage ^0.3.6, version solving failed.
pub get failed (1)
Process finished with exit code 1```

**Comment by GroovinChip** [comment]
Um. I don't know how to resolve merge conflicts, any suggestions?

**Comment by GregorySech** [comment]
Merge conflicts resolved, must use flutter 0.6.0 to test the PR.

**Comment by GregorySech** [comment]
some more updates

**Pull request merged**
